const baseUrl = (process.env.NEXT_PUBLIC_API_URL || process.env.NEXT_PUBLIC_ATLAS_API_URL || (process.env.NODE_ENV === "production" ? "" : "http://localhost:8001")).replace(/\/$/, "");

export type Project = { id: string; name: string };
export type Citation = { document_id: string; filename: string; page: number; section: string };
export type SupportingSpan = { text: string; start: number; end: number };
export type AnswerCitation = Citation & { citation_id: string; chunk_id: string; supporting_spans: SupportingSpan[] };
export type AnswerClaim = { text: string; type: "fact" | "calculation" | "recommendation"; citation_ids: string[]; support_status: "SUPPORTED" | "PARTIAL" | "UNSUPPORTED" };
export type ConflictingSource = { document_key: string; section: string; document_ids: string[]; revisions: string[] };
export type WorkflowTrace = { stage_latency_ms: Record<string, number>; candidate_chunk_ids: string[]; selected_chunk_ids: string[]; context_tokens: number; retry_count: number; final_status: "ANSWERED" | "PARTIAL" | "CONFLICTING_EVIDENCE" | "INSUFFICIENT_EVIDENCE" | null };
export type Document = { id: string; project_id: string; filename: string; document_type: string; status: string; page_count: number | null; metadata: Record<string, unknown> };
export type Ingestion = { id: string; document_id: string; status: string; chunk_count: number; attempt_count: number; error: string | null };
export type UploadResult = { document: Document; ingestion: Ingestion };
export type CopilotResult = { answer: string; rewritten_question: string; citations: AnswerCitation[]; claims: AnswerClaim[]; confidence: number; status: "ANSWERED" | "PARTIAL" | "CONFLICTING_EVIDENCE" | "INSUFFICIENT_EVIDENCE"; missing_information: string[]; conflicting_sources: ConflictingSource[]; trace: WorkflowTrace };
export type ComplianceFinding = { id: string; equipment_id: string; parameter: string; requirement: string; required_value: string; observed_value: string | null; normalized_unit: string | null; status: string; severity: string; explanation: string; specification_citation: Citation; submittal_citation: Citation | null; confidence: number; review_status: string; reviewer_note: string | null; reviewer_id: string | null };
export type ScheduleRisk = { affected_task: string; affected_task_name: string; root_cause: string; dependency_chain: string[]; predicted_delay_days: number; available_float_days: number; risk_lead_time_days: number; severity: string; mitigation_options: string[]; explanation: string; assumptions: string[]; evidence: Citation[] };
export type RfiMatch = { label: string; similarity_score: number; shared_equipment: string[]; shared_specification_references: string[]; previous_answer: string; citation: Citation };
export type ProcedureStep = { index: number; equipment_id: string; prerequisite: string[]; instruction: string; acceptance_criterion: string; observation: string | null; evidence: string[]; status: "NOT_STARTED" | "READY" | "BLOCKED" | "PASS" | "FAIL" | "NEEDS_REVIEW"; reviewer_note: string | null; citation: Citation };
export type Procedure = { document_id: string; filename: string; equipment_id: string; steps: ProcedureStep[] };
export type TestRecord = { id: string; procedure_document_id: string; status: "pass" | "fail" | "needs_review"; completed_steps: number; total_steps: number; coverage_percent: number; automation_coverage_percent: number; steps: ProcedureStep[]; non_conformances: Array<{ id: string; step_index: number; criterion: string; observation: string; citation: Citation; status: string }> };
export type Graph = { project_id: string; nodes: Array<{ id: string; type: string; [key: string]: unknown }>; edges: Array<{ source: string; target: string; [key: string]: unknown }> };
export type ProcurementDashboard = { mode: "demo_mock"; live_data_available: false; disclaimer: string; cards: Array<{ equipment_tag: string; vendor: string; purchase_order_status: string; planned_delivery: string; forecast_delivery: string | null; lead_time_days: number | null; delay_days: number | null; risk_level: string; data_source: string; live_tracking: false }>; integrations: Array<{ integration: string; status: "roadmap_unavailable"; message: string }> };
export type ThreadDocument = { id: string; filename: string; document_type: string; status: string; revision: string | null; approval_status: string | null };
export type DigitalThread = { project_id: string; equipment: { equipment_id: string; name: string; equipment_type: string | null; status: string; metadata: Record<string, unknown> }; current_specification: ThreadDocument | null; current_submittal: ThreadDocument | null; requirements: Array<Record<string, unknown>>; compliance_findings: ComplianceFinding[]; rfis: Array<Record<string, unknown>>; vendor: Array<Record<string, unknown>>; shipments: Array<Record<string, unknown>>; schedule_tasks: Array<Record<string, unknown>>; commissioning_status: Array<Record<string, unknown>>; open_ncrs: Array<Record<string, unknown>>; mitigation_scenarios: Array<Record<string, unknown>>; evidence_links: Array<Record<string, unknown>> };
export type Readiness = { project_id: string; equipment_id: string; score: number; status: "READY" | "NEEDS_REVIEW" | "NOT_READY"; rules: Array<{ rule: string; weight: number; satisfied: boolean; score: number; evidence: string }> };
export type AlternativeOption = { name: string; option_type: "supplier" | "route"; recovery_days: number; assumptions: string[] };
export type Shipment = { shipment_id: string; reference: string; equipment_id: string; status: string; origin: string; destination: string; planned_arrival: string; forecast_arrival: string; supplier_tiers: Array<{ tier: number; supplier: string; location: string }>; milestones: Array<{ name: string; planned_date: string; forecast_date: string; status: string }>; schedule_task_id: string; schedule_float_days: number; critical_path: boolean; alternatives: AlternativeOption[]; synthetic_simulation: true; live_tracking: false; live_position: null };
export type ShipmentList = { synthetic_simulation: true; disclaimer: string; shipments: Shipment[] };
export type ShipmentRisk = { shipment_id: string; reference: string; equipment_id: string; schedule_task_id: string; forecast_delay_days: number; available_schedule_float_days: number; schedule_float_consumed_days: number; critical_path_impact_days: number; severity: string; alert_latency_minutes: number | null; alternative_option: AlternativeOption | null; risk_events: Array<{ event_id: string; event_type: string; description: string; occurred_at: string; alert_generated_at: string; forecast_delay_days: number; alert_latency_minutes: number }>; synthetic_simulation: true; disclaimer: string; live_position: null };
export type AlternativeComparison = { shipment_id: string; baseline_delay_days: number; options: Array<{ option: AlternativeOption; residual_delay_days: number; critical_path_impact_days: number; severity: string }>; recommended_option: AlternativeOption | null; synthetic_simulation: true; disclaimer: string };
export type SupplyAssessment = { shipment_id: string; equipment_id: string; vendor: string; planned_date: string; current_eta: string; required_on_site_date: string; status: string; location: string; eta_variance_days: number; available_float_days: number; schedule_exposure_days: number; severity: string; affected_task: string | null; first_alert_at: string | null; alert_lead_time_days: number | null; impact_event_id: string | null; data_source: "project_supplied_csv"; live_tracking: false };
export type ShipmentTimeline = { shipment_id: string; project_id: string; equipment_id: string; events: Array<{ id: string; event_type: string; status: string; location: string | null; event_at: string; details: Record<string, unknown> }> };
export type CounterfactualScenario = { id: string; key: "do_nothing" | "expedite_shipment" | "resequence_installation"; action: string; assumptions: string[]; projected_delay_days: number; critical_path_exposure_days: number; commissioning_date: string | null; readiness_impact: { current_score: number; projected_score: number; score_delta: number; basis: string }; additional_cost: number | null; residual_risk: string; evidence_references: Array<Record<string, unknown>>; confidence: number };
export type MitigationSimulation = { simulation_id: string; project_id: string; equipment_id: string; shipment_id: string; impact_event_id: string; baseline_delay_days: number; baseline_exposure_days: number; scenarios: CounterfactualScenario[] };
export type MitigationSelection = { simulation_id: string; selected: CounterfactualScenario; recalculated_impact_chain: { source_event_id: string; shipment_id: string; equipment_id: string; selected_scenario_id: string; projected_schedule_delay_days: number; projected_critical_path_exposure_days: number; projected_commissioning_date: string | null; projected_readiness_score: number; residual_risk: string; evidence_references: Array<Record<string, unknown>> } };
export type ImpactChain = { chain_id: string; project_id: string; finding_id: string; equipment_id: string; finding_parameter: string; finding_required_value: string; finding_observed_value: string | null; procurement: { shipment_id: string; shipment_reference: string; replacement_lead_time_days: number; current_forecast_delay_days: number; schedule_task_id: string }; schedule: { affected_task: string; available_float_days: number; predicted_delay_days: number; critical_path_impact_days: number; affected_completion_date: string; severity: string; evidence: Array<Record<string, unknown>> }; commissioning_readiness: Readiness; mitigation_scenarios: Array<{ id: string; action: string; days_recovered: number; added_cost: number; remaining_delay: number; remaining_risk: string; assumptions: string[]; confidence: number; evidence: Array<Record<string, unknown>> }>; status: "AWAITING_HUMAN_DECISION" | "ACTION_CREATED"; human_decision: { action: string; scenario_id: string | null; note: string | null } | null; approved_action: { id: string; action: string; scenario_id: string | null; status: string; created_record_id: string | null; note: string | null } | null; evidence_chain: Array<Record<string, unknown>> };
export type EvaluationCase = { id: string; case_key: string; category: "compliance" | "rag"; status: string; expected: Record<string, unknown>; actual: Record<string, unknown>; metrics: Record<string, number | boolean>; error: string | null };
export type EvaluationRun = { id: string; project_id: string; fixture_name: string; fixture_format: "json" | "csv"; synthetic_data: boolean; status: string; metrics: { compliance: Record<string, number>; rag: Record<string, number> }; error: string | null; started_at: string; completed_at: string | null; cases: EvaluationCase[] };
export type WorkflowType = "rfi_search" | "submittal_review" | "schedule_impact_tracing" | "commissioning_checklist_preparation" | "coordination_report_preparation";
export type WorkflowBenchmark = { id: string; project_id: string; workflow_type: WorkflowType; manual_baseline_seconds: number; atlas_execution_seconds: number; measurement_source: string; sample_count: number; measurement_kind: "measured" | "projected"; timestamp: string; synthetic_data: boolean; hours_saved: number; total_hours_saved: number };
export type BenchmarkSummary = { project_id: string; measured_hours_saved: number; projected_monthly_hours_saved: number; measured_sample_count: number; projected_monthly_sample_count: number; record_count: number; synthetic_data_present: boolean; label: string; workflows: Array<{ workflow_type: WorkflowType; measured_hours_saved: number; projected_monthly_hours_saved: number; measured_sample_count: number; projected_monthly_sample_count: number }> };
export type ExecutiveSummary = { project_id: string; critical_deviations: number; equipment_at_risk: number; schedule_exposure_days: number; supply_chain_alerts: number; commissioning_readiness: number | null; open_ncrs: number; measured_hours_saved: number; projected_monthly_hours_saved: number; recommended_mitigation: string | null; evidence_confidence: number | null; synthetic_data: boolean };

export class ApiError extends Error {
  constructor(message: string, public status: number) { super(message); }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { ...(init?.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...init?.headers } });
  if (!response.ok) {
    const body = await response.json().catch(() => null) as { error?: { message?: string } } | null;
    throw new ApiError(body?.error?.message ?? `Request failed (${response.status})`, response.status);
  }
  return response.json() as Promise<T>;
}

export const api = {
  health: () => request<{ status: string; components: Record<string, string> }>("/health"),
  projects: () => request<Project[]>("/projects"),
  createProject: (name: string) => request<Project>("/projects", { method: "POST", body: JSON.stringify({ name }) }),
  documents: (projectId: string) => request<Document[]>(`/projects/${projectId}/documents`),
  upload: (projectId: string, type: string, file: File) => {
    const body = new FormData(); body.set("document_type", type); body.set("file", file);
    return request<UploadResult>(`/projects/${projectId}/documents`, { method: "POST", body });
  },
  copilot: (projectId: string, question: string, history: Array<{ role: "user" | "assistant"; content: string }>) => request<CopilotResult>(`/projects/${projectId}/copilot`, { method: "POST", body: JSON.stringify({ question, history }) }),
  compliance: (projectId: string, specification_document_id: string, submittal_document_id: string) => request<{ findings: ComplianceFinding[] }>(`/projects/${projectId}/compliance/checks`, { method: "POST", body: JSON.stringify({ specification_document_id, submittal_document_id }) }),
  complianceFindings: (projectId: string) => request<{ findings: ComplianceFinding[] }>(`/projects/${projectId}/compliance/findings`),
  reviewFinding: (projectId: string, findingId: string, decision: "approved" | "rejected" | "needs_review", reviewer_note?: string) => request<ComplianceFinding>(`/projects/${projectId}/compliance/findings/${findingId}/review`, { method: "PATCH", body: JSON.stringify({ decision, reviewer_note }) }),
  schedule: (projectId: string, schedule_document_id: string) => request<{ risks: ScheduleRisk[]; assumptions: string[] }>(`/projects/${projectId}/schedule/analysis`, { method: "POST", body: JSON.stringify({ schedule_document_id }) }),
  rfiMatches: (projectId: string, proposed_rfi: string) => request<{ matches: RfiMatch[] }>(`/projects/${projectId}/rfis/matches`, { method: "POST", body: JSON.stringify({ proposed_rfi }) }),
  procedure: (projectId: string, documentId: string) => request<Procedure>(`/projects/${projectId}/commissioning/procedures/${documentId}`),
  recordTest: (projectId: string, procedure_document_id: string, observations: Array<{ step_index: number; observation: string; evidence?: string[]; reviewer_note?: string; prerequisites_met?: boolean }>) => request<TestRecord>(`/projects/${projectId}/commissioning/records`, { method: "POST", body: JSON.stringify({ procedure_document_id, observations }) }),
  readiness: (projectId: string, equipmentId: string) => request<Readiness>(`/projects/${projectId}/commissioning/readiness/${encodeURIComponent(equipmentId)}`),
  digitalThread: (projectId: string, equipmentId: string) => request<DigitalThread>(`/projects/${projectId}/equipment/${encodeURIComponent(equipmentId)}/digital-thread`),
  seedSupplyChain: (projectId: string) => request<ShipmentList>(`/projects/${projectId}/supply-chain/seed`, { method: "POST" }),
  resetDemo: (projectId: string) => request<ShipmentList>(`/projects/${projectId}/demo/reset`, { method: "POST" }),
  seedVerticalScenario: (projectId: string) => request(`/projects/${projectId}/demo/vertical-scenario`, { method: "POST" }),
  executiveSummary: (projectId: string) => request<ExecutiveSummary>(`/projects/${projectId}/executive-summary`),
  shipments: (projectId: string) => request<ShipmentList>(`/projects/${projectId}/supply-chain/shipments`),
  shipmentRisk: (projectId: string, shipmentId: string) => request<ShipmentRisk>(`/projects/${projectId}/supply-chain/shipments/${shipmentId}/risk`),
  shipmentAlternatives: (projectId: string, shipmentId: string) => request<AlternativeComparison>(`/projects/${projectId}/supply-chain/shipments/${shipmentId}/alternatives`),
  injectRisk: (projectId: string, shipmentId: string, payload: { event_type: string; description: string; occurred_at: string; alert_generated_at: string; forecast_delay_days: number }) => request(`/projects/${projectId}/supply-chain/shipments/${shipmentId}/risk-events`, { method: "POST", body: JSON.stringify(payload) }),
  importSupplyChain: (projectId: string, file: File) => { const body = new FormData(); body.set("file", file); return request<{ filename: string; imported: number; assessments: SupplyAssessment[]; live_tracking: false }>(`/projects/${projectId}/supply-chain/import`, { method: "POST", body }); },
  supplyAssessments: (projectId: string) => request<SupplyAssessment[]>(`/projects/${projectId}/supply-chain/assessments`),
  supplyAlerts: (projectId: string) => request<SupplyAssessment[]>(`/projects/${projectId}/supply-chain/alerts`),
  assessShipment: (projectId: string, shipmentId: string) => request<SupplyAssessment>(`/projects/${projectId}/supply-chain/shipments/${shipmentId}/assessment`, { method: "POST" }),
  shipmentTimeline: (projectId: string, shipmentId: string) => request<ShipmentTimeline>(`/projects/${projectId}/supply-chain/shipments/${shipmentId}/timeline`),
  startImpact: (projectId: string, payload: { compliance_finding_id: string; shipment_id: string; schedule_document_id: string; replacement_lead_time_days: number; replacement_cost: number; analysis_date: string }) => request<ImpactChain>(`/projects/${projectId}/impact-chains`, { method: "POST", body: JSON.stringify(payload) }),
  decideImpact: (projectId: string, chainId: string, payload: { action: "APPROVE" | "REJECT" | "REQUEST_REVIEW" | "CREATE_RFI" | "CREATE_NCR"; scenario_id?: string; note?: string }) => request<ImpactChain>(`/projects/${projectId}/impact-chains/${chainId}/decision`, { method: "POST", body: JSON.stringify(payload) }),
  graph: (projectId: string) => request<Graph>(`/projects/${projectId}/graph`),
  procurement: (projectId: string, items: Array<{ equipment_tag: string; vendor: string; purchase_order_status: string; planned_delivery: string; forecast_delivery?: string; lead_time_days?: number }>) => request<ProcurementDashboard>(`/projects/${projectId}/procurement/dashboard`, { method: "POST", body: JSON.stringify({ items }) }),
  runEvaluation: (projectId: string, fixture_format: "json" | "csv" = "json") => request<EvaluationRun>("/api/evaluation/run", { method: "POST", body: JSON.stringify({ project_id: projectId, fixture_name: "synthetic_small", fixture_format }) }),
  evaluationRun: (projectId: string, runId: string) => request<EvaluationRun>(`/api/evaluation/runs/${runId}?project_id=${encodeURIComponent(projectId)}`),
  simulateMitigations: (payload: { project_id: string; shipment_id: string; impact_event_id: string; rules: { expedite_recovery_days?: number; expedite_additional_cost?: number; resequence_recovery_days?: number; resequence_additional_cost?: number } }) => request<MitigationSimulation>("/api/mitigations/simulate", { method: "POST", body: JSON.stringify(payload) }),
  selectMitigation: (projectId: string, simulationId: string, scenario_key: CounterfactualScenario["key"]) => request<MitigationSelection>(`/api/mitigations/${simulationId}/select`, { method: "POST", body: JSON.stringify({ project_id: projectId, scenario_key }) }),
  recordBenchmark: (payload: { project_id: string; workflow_type: WorkflowType; manual_baseline_seconds: number; atlas_execution_seconds: number; measurement_source: string; sample_count: number; measurement_kind: "measured" | "projected"; timestamp?: string; synthetic_data: boolean }) => request<WorkflowBenchmark>("/api/benchmarks", { method: "POST", body: JSON.stringify(payload) }),
  benchmarkSummary: (projectId: string) => request<BenchmarkSummary>(`/api/benchmarks/summary?project_id=${encodeURIComponent(projectId)}`),
};

export const apiBaseUrl = baseUrl;
